apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyDeployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
       - name: nginx
         image: nginx:latest
