apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-backend
  labels:
    website: e-commerce-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      website: e-commerce-backend
  template:
    metadata:
      name: pod-backend
      labels:
        website: e-commerce-backend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
      nodeSelector:
        app: website
