apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-admins-access
  namespace: default
subjects:
- kind: Group
  name: web-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin-access
  apiGroup: rbac.authorization.k8s.io