apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-frontend
  labels:
    website: e-commerce
spec:
  replicas: 3
  selector:
    matchLabels:
      website: e-commerce
  template:
    metadata:
      name: pod-frontend
      labels:
        website: e-commerce
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.22.1
  
